#ifdef ADDRESS_SPACE_INPUTS
#undef ADDRESS_SPACE_INPUTS
#undef ADDRESS_SPACE_CONTEXT
#undef APPEND_ADDRESS_SPACE
#undef DO_RESERVE_STATIC_CONST
#endif 

#define ADDRESS_SPACE_INPUTS __global
#define ADDRESS_SPACE_CONTEXT __constant
#define APPEND_ADDRESS_SPACE(X) X ## __constant__global
#define DO_RESERVE_STATIC_CONST



