#ifdef ADDRESS_SPACE_ONE
#undef ADDRESS_SPACE_CONSTANT
#undef ADDRESS_SPACE_ONE
#undef ADDRESS_SPACE_TWO
#undef APPEND_ADDRESS_SPACE
#undef APPEND_ADDRESS_SPACE_ONE
#undef APPEND_ADDRESS_SPACE_TWO
#endif

#define ADDRESS_SPACE_CONSTANT __constant
#define ADDRESS_SPACE_ONE 
#define ADDRESS_SPACE_TWO 
#define APPEND_ADDRESS_SPACE(X) X
#define APPEND_ADDRESS_SPACE_ONE(X) X
#define APPEND_ADDRESS_SPACE_TWO(X) X
