#ifdef ADDRESS_SPACE_INPUTS
#undef ADDRESS_SPACE_INPUTS
#undef ADDRESS_SPACE_CONTEXT
#undef APPEND_ADDRESS_SPACE
#ifdef DO_RESERVE_STATIC_CONST
#undef DO_RESERVE_STATIC_CONST
#endif 
#endif 

#define ADDRESS_SPACE_INPUTS
#define ADDRESS_SPACE_CONTEXT
#define APPEND_ADDRESS_SPACE(X) X


