#ifdef ADDRESS_SPACE_INPUTS
#undef ADDRESS_SPACE_CONSTANT
#undef ADDRESS_SPACE_CONTEXT
#undef ADDRESS_SPACE_INPUTS
#undef APPEND_ADDRESS_SPACE
#undef APPEND_ADDRESS_SPACE_INPUTS
#undef DO_RESERVE_STATIC_CONST
#endif 

#define ADDRESS_SPACE_CONSTANT __constant
#define ADDRESS_SPACE_CONTEXT __constant
#define ADDRESS_SPACE_INPUTS __global
#define APPEND_ADDRESS_SPACE(X) X ## __constant__constant__global
#define APPEND_ADDRESS_SPACE_INPUTS(X) X ## __global
#define DO_RESERVE_STATIC_CONST



